# Generated by Django 4.0.1 on 2024-02-27 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('año', models.DateField()),
                ('direccion', models.CharField(max_length=40)),
                ('ciudad', models.CharField(max_length=40)),
                ('pais', models.CharField(max_length=30)),
                ('portada', models.ImageField(upload_to='portadas')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Vino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('año', models.DateField()),
                ('origen', models.CharField(max_length=40)),
                ('portada', models.ImageField(upload_to='portadas')),
                ('sitioweb', models.URLField()),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiendavinos.bodega')),
                ('categorias', models.ManyToManyField(to='tiendavinos.Categoria')),
            ],
        ),
    ]
