# Generated by Django 4.0.1 on 2024-02-27 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendavinos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bodega',
            old_name='ciudad',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='vino',
            old_name='origen',
            new_name='pais',
        ),
        migrations.AlterField(
            model_name='bodega',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
