# Generated by Django 4.0.1 on 2024-03-03 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendavinos', '0002_rename_ciudad_bodega_estado_rename_origen_vino_pais_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodega',
            name='portada',
        ),
        migrations.AddField(
            model_name='vino',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
