# Generated by Django 4.0.1 on 2024-03-03 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendavinos', '0003_remove_bodega_portada_vino_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
